server:
  port: 9012


 
eureka:
  instance:
    hostname: localhost
  
spring:
  application:
    name: student-api
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
        - id: student-details
          uri: lb://student-details
          predicates:
            - Path=/details/**

